### ISSUE TITLE
Deccan Delight

### ISSUE THREAD

**Issue by gaja71** [Gujal00/GujalKodiWork#11] opened 2017-11-10 17:40 UTC
Hi Gujal,
DD is not working. Any issues? Hope to see it live and running. 
Thanks very much for your super efforts. 
Regards,
Gaja

**Comment by Gujal00** [comment] 2017-11-10 23:14
Just saying DD not working is not helpful. There are close to 30 scrapers in it and need to say which one is not working. Let me know the exact issue so that I can see where the issue is

**Comment by gaja71** [comment] 2017-11-11 16:33
Sorry , i was unable to open DD. Failed to load was the msg.  It's working now. Specific scraper MHDTV live : various live tv-Malayalam no channels working. Thanks.

**Comment by Gujal00** [comment] 2017-11-11 21:04
Yes, MHDTV live is not working in DD because MHDTV are no longer providing free access. Can't do anything unless they open up free access as before.
Goto their website at `http://mhdtvlive.co.in/malayalam-entertainment/` and click on any channel and you can see that they need subscription now.

**Comment by gaja71** [comment] 2017-11-11 21:55
Thanks Gujal.

**Comment by Gujal00** [comment] 2017-11-14 04:25
Okay, found a different source thoptv. Use that instead of mhdtv. Will be in 1.3.8 release

**Closed by Gujal00** 2017-11-14 04:25 UTC
Labels: question, wontfix

**Comment by gaja71** [comment] 2017-11-14 15:36
Thanks Gujal, looking forward to the release. 👍

**Comment by Gujal00** [comment] 2017-11-14 21:32
You should have got the release by now, it was released 8 hours before you posted the above reply

**Comment by gaja71** [comment] 2017-11-14 22:02
Updated the new release version, got Thop. Thanks very much Gujal. Much appreciated your good work. 👍☺
